---
label: Project
hide_body: true
fields:
- name: project_name
  type: text
  config:
    required: true
    min: 2
  label: Project Name
  default: My Project
- name: project_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
    min: 0
    max: 150
  label: Project Description
